LABELS = {
    "ru": {
        "structure": "Структура",
        "report": "Заключение Delphi",
        "documents": "Документы",
        "before": "До",
        "after": "После",
        "context": "Контекст",
        "confirmed": "Подтверждено",
        "unreviewed": "Не проверено",
        "needs_clarification": "Требует уточнения",
        "rejected": "Отклонено — исключено из выводов",
        "evidence": "Источники",
        "recommendation": "Рекомендация",
        "note": "Заметка проверяющего",
        "coverage": "Покрытие обработки",
        "errors": "Ограничения и ошибки",
        "revision": "Версия проверки",
        "completed": "Обработка завершена",
        "partial": "Частичный результат",
        "findings": "Выводов",
        "active": "Не отклонено",
        "none": "Нет",
        "clause": "Пункт",
        "position": "Позиция",
        "function": "Функция",
        "side": "Сторона",
        "owners": "Подразделения",
        "actor": "Исполнитель",
        "action": "Действие",
        "object": "Объект",
        "scope": "Область",
        "condition": "Условие",
        "modality": "Обязательность",
        "review": "Проверка",
        "original": "Текст источников и заметки сохранены на исходном языке.",
        "search": "Поиск в предоставленном комплекте «После»",
        "search_before": "Поиск в предоставленном комплекте «До»",
        "search_new_incomplete": "Поиск неполный: появление новой функции не установлено",
        "search_complete": "Все доступные источники проверены",
        "search_incomplete": "Поиск неполный: потеря функции не установлена",
        "search_sources": "Проверено исходных блоков",
        "search_candidates": "Возможные соответствия для проверки",
        "search_scope": "Поиск ограничен предоставленными документами и не доказывает прекращения деятельности организации.",
    },
    "kk": {
        "structure": "Құрылым",
        "report": "Delphi қорытындысы",
        "documents": "Құжаттар",
        "before": "Дейін",
        "after": "Кейін",
        "context": "Мәнмәтін",
        "confirmed": "Расталған",
        "unreviewed": "Тексерілмеген",
        "needs_clarification": "Нақтылау қажет",
        "rejected": "Қабылданбаған — қорытындыдан шығарылған",
        "evidence": "Дереккөздер",
        "recommendation": "Ұсыныс",
        "note": "Тексерушінің ескертпесі",
        "coverage": "Өңдеу қамтуы",
        "errors": "Шектеулер мен қателер",
        "revision": "Тексеру нұсқасы",
        "completed": "Өңдеу аяқталды",
        "partial": "Ішінара нәтиже",
        "findings": "Тұжырымдар",
        "active": "Қабылданбағандардан басқа",
        "none": "Жоқ",
        "clause": "Тармақ",
        "position": "Орны",
        "function": "Функция",
        "side": "Тарап",
        "owners": "Бөлімшелер",
        "actor": "Орындаушы",
        "action": "Әрекет",
        "object": "Нысан",
        "scope": "Қолданылу аясы",
        "condition": "Шарт",
        "modality": "Міндеттілік",
        "review": "Тексеру",
        "original": "Дереккөз мәтіні мен ескертпелер бастапқы тілде сақталған.",
        "search": "Берілген «Кейін» құжаттар жиынтығынан іздеу",
        "search_before": "Берілген «Бұрын» құжаттар жиынтығынан іздеу",
        "search_new_incomplete": "Іздеу толық емес: жаңа функцияның пайда болуы анықталған жоқ",
        "search_complete": "Барлық қолжетімді дереккөздер тексерілді",
        "search_incomplete": "Іздеу толық емес: функцияның жоғалғаны анықталған жоқ",
        "search_sources": "Тексерілген бастапқы блоктар",
        "search_candidates": "Тексеруді қажет ететін ықтимал сәйкестіктер",
        "search_scope": "Іздеу берілген құжаттармен шектеледі және ұйым қызметінің тоқтағанын дәлелдемейді.",
    },
    "en": {
        "structure": "Structure",
        "report": "Delphi conclusion",
        "documents": "Documents",
        "before": "Before",
        "after": "After",
        "context": "Context",
        "confirmed": "Confirmed",
        "unreviewed": "Unreviewed",
        "needs_clarification": "Needs clarification",
        "rejected": "Rejected — excluded from conclusions",
        "evidence": "Evidence",
        "recommendation": "Recommendation",
        "note": "Reviewer note",
        "coverage": "Processing coverage",
        "errors": "Limitations and errors",
        "revision": "Review revision",
        "completed": "Processing completed",
        "partial": "Partial result",
        "findings": "Findings",
        "active": "Not rejected",
        "none": "None",
        "clause": "Clause",
        "position": "Position",
        "function": "Function",
        "side": "Side",
        "owners": "Units",
        "actor": "Actor",
        "action": "Action",
        "object": "Object",
        "scope": "Scope",
        "condition": "Condition",
        "modality": "Modality",
        "review": "Review",
        "original": "Source quotations and reviewer notes remain in their original language.",
        "search": "Search of the supplied After set",
        "search_before": "Search of the supplied Before set",
        "search_new_incomplete": "Search is incomplete: a new duty has not been established",
        "search_complete": "All available sources reviewed",
        "search_incomplete": "Search is incomplete: a missing duty has not been established",
        "search_sources": "Source blocks reviewed",
        "search_candidates": "Possible matches requiring review",
        "search_scope": "The search covers only the supplied documents and does not prove that the organization stopped an activity.",
    },
}
