LABELS = {
    "ru": {
        "report": "Заключение Delphi",
        "documents": "Документы",
        "before": "До",
        "after": "После",
        "context": "Контекст",
        "confirmed": "Подтверждено",
        "unreviewed": "Не проверено",
        "needs_clarification": "Требует уточнения",
        "rejected": "Отклонено — исключено из выводов",
        "evidence": "Источники",
        "recommendation": "Рекомендация",
        "note": "Заметка проверяющего",
        "coverage": "Покрытие обработки",
        "errors": "Ограничения и ошибки",
        "revision": "Версия проверки",
        "completed": "Обработка завершена",
        "partial": "Частичный результат",
        "findings": "Выводов",
        "active": "Не отклонено",
        "none": "Нет",
        "clause": "Пункт",
        "position": "Позиция",
        "function": "Функция",
        "side": "Сторона",
        "owners": "Подразделения",
        "actor": "Исполнитель",
        "action": "Действие",
        "object": "Объект",
        "scope": "Область",
        "condition": "Условие",
        "modality": "Обязательность",
        "review": "Проверка",
        "original": "Текст источников и заметки сохранены на исходном языке.",
    },
    "kk": {
        "report": "Delphi қорытындысы",
        "documents": "Құжаттар",
        "before": "Дейін",
        "after": "Кейін",
        "context": "Мәнмәтін",
        "confirmed": "Расталған",
        "unreviewed": "Тексерілмеген",
        "needs_clarification": "Нақтылау қажет",
        "rejected": "Қабылданбаған — қорытындыдан шығарылған",
        "evidence": "Дереккөздер",
        "recommendation": "Ұсыныс",
        "note": "Тексерушінің ескертпесі",
        "coverage": "Өңдеу қамтуы",
        "errors": "Шектеулер мен қателер",
        "revision": "Тексеру нұсқасы",
        "completed": "Өңдеу аяқталды",
        "partial": "Ішінара нәтиже",
        "findings": "Тұжырымдар",
        "active": "Қабылданбағандардан басқа",
        "none": "Жоқ",
        "clause": "Тармақ",
        "position": "Орны",
        "function": "Функция",
        "side": "Тарап",
        "owners": "Бөлімшелер",
        "actor": "Орындаушы",
        "action": "Әрекет",
        "object": "Нысан",
        "scope": "Қолданылу аясы",
        "condition": "Шарт",
        "modality": "Міндеттілік",
        "review": "Тексеру",
        "original": "Дереккөз мәтіні мен ескертпелер бастапқы тілде сақталған.",
    },
    "en": {
        "report": "Delphi conclusion",
        "documents": "Documents",
        "before": "Before",
        "after": "After",
        "context": "Context",
        "confirmed": "Confirmed",
        "unreviewed": "Unreviewed",
        "needs_clarification": "Needs clarification",
        "rejected": "Rejected — excluded from conclusions",
        "evidence": "Evidence",
        "recommendation": "Recommendation",
        "note": "Reviewer note",
        "coverage": "Processing coverage",
        "errors": "Limitations and errors",
        "revision": "Review revision",
        "completed": "Processing completed",
        "partial": "Partial result",
        "findings": "Findings",
        "active": "Not rejected",
        "none": "None",
        "clause": "Clause",
        "position": "Position",
        "function": "Function",
        "side": "Side",
        "owners": "Units",
        "actor": "Actor",
        "action": "Action",
        "object": "Object",
        "scope": "Scope",
        "condition": "Condition",
        "modality": "Modality",
        "review": "Review",
        "original": "Source quotations and reviewer notes remain in their original language.",
    },
}
